### ISSUE TITLE
Layout do Aplicativo

### ISSUE THREAD

**Issue by nicholasess** [training-center/mentoria-mobileapp#2]
Vocês já tem o layout do aplicativo em PSD ou similar?

**Comment by woliveiras** [comment]
@nicholasess, mil perdões pela demora em responder.

Não temos não.

Na realidade isso foi uma ideia que veio, demorou um pouco e acabou caindo no esquecimento.

Como agora o mentoria vai mudar, teremos que segurar um pouco aqui.
